
var FCAPP=FCAPP||{};FCAPP.ADDetail=FCAPP.ADDetail||{RUNTIME:{picCount:0,LI:{}},init:function(){var R=ADDetail.RUNTIME;if(!window.gQuery||!gQuery.adid){setTimeout(arguments.callee,200);return;}
ADDetail.initElements();ADDetail.initEvent();ADDetail.loadADDetailData();FCAPP.Common.hideToolbar();FCAPP.Common.loadShareData(gQuery.adid);},initElements:function(){var R=ADDetail.RUNTIME;if(!R.template){R.container=$('#container');R.template=FCAPP.Common.escTpl($('#template').html());R.popTips=$('div.pop_tips');R.btnBack=$("#btnBack");var from=window.gQuery&&gQuery.from?gQuery.from:'';if(from.length==0){R.btnBack.hide();}else{R.btnBack.show();}}},initEvent:function(){var R=ADDetail.RUNTIME;$(window).resize(function(){FCAPP.Common.resizeLayout(R.popTips);ADDetail.resizeLayout();});R.btnBack.bind("click",function(){event.cancelBubble=true;var from=window.gQuery&&gQuery.from?gQuery.from:'';if(window.gQuery&&gQuery.from)delete gQuery.from;if(window.gQuery&&gQuery.adid)delete gQuery.adid;FCAPP.Common.jumpTo(from,{},true);});},loadADDetailData:function(){window.renderData=ADDetail.renderData;var datafile=window.gQuery&&gQuery.adid?gQuery.adid+'.':'',dt=new Date();datafile=datafile.replace(/[<>\'\"\/\\&#\?\s\r\n]+/gi,'');datafile+='ad-desc.js?';$.ajax({url:'static/'+datafile+dt.getDate()+dt.getHours(),dataType:'jsonp'});},renderData:function(data){var R=ADDetail.RUNTIME,id=window.gQuery&&gQuery.id?gQuery.id:'';data.id=id;R.stData=data;FCAPP.Common.hideLoading();data.rooms=ADDetail.sortCategory(data.rooms);R.container.html($.template(R.template,{data:data}));if(data.video&&data.video.vid){setTimeout(function(){ADDetail.showVideo(data.video);},500);}else{$('#videoDiv').parent().hide();}
if(data.banner){FCAPP.Common.loadImg(data.banner,'bannerPic',function(img){img.width=720;img.height=175;img.id=img.idx;$('#actTop').show();});}},showVideo:function(info){var video=new tvp.VideoInfo(),player=new tvp.Player(info.width,info.height),type=typeof(navigator.plugins['Shockwave Flash'])=='undefined'?"html5":'auto',agent=navigator.userAgent;if(/MI [2-9]/.test(agent)&&typeof(navigator.plugins['Shockwave Flash'])!='undefined'){type="flash";}
if(type!='auto'){player.addParam("player",type);}
video.setVid(info.vid);console.log(info.vid);if(info.pic){player.addParam("pic",info.pic);}
if(video.title){video.setTitle(info.title);}
player.addParam("showcfg","0");player.addParam("searchbar","0");player.addParam("showend","0");player.addParam("autoplay","0");player.setCurVideo(video);player.write("videoDiv");window.videoPlayer=player;},sortCategory:function(rooms){var tmp=[],category={},newCategory=[],key,other,i,defaultDesc='其他户型';for(i=0,il=rooms.length;i<il;i++){if(!rooms[i].desc){rooms[i].desc=defaultDesc;}
if(rooms[i].desc in category){category[rooms[i].desc].push(rooms[i]);}else{category[rooms[i].desc]=[rooms[i]];}}
for(i in category){tmp.push({key:i,len:category[i].length});}
tmp.sort(function(a,b){return b.len-a.len;});for(i=0,il=tmp.length;i<il;i++){key=tmp[i].key;if(key!==defaultDesc){newCategory.push({key:key,rooms:category[key]});}}
if(category[defaultDesc]&&category[defaultDesc].length>0){newCategory.push({key:defaultDesc,rooms:category[defaultDesc]});}
tmp=null;category=null;return newCategory;},showDetail:function(houseid,id){FCAPP.Common.jumpTo('picroll.html',{houseid:houseid,id:id,refer:location.pathname.split("/").pop()},true);},switchList:function(obj,len,idx){var R=ADDetail.RUNTIME.LI,box=obj.parentNode;if(!R['boxLiBox'+idx]){R['boxLiBox'+idx]=$('#box'+idx+' div.box_type');R['boxPhoto'+idx]=$('#box'+idx+' div.house_photo');R['boxLi'+idx]=$('#box'+idx+' li');}
if(box.className.indexOf("box_up")!=-1){R['boxLiBox'+idx].css('height','auto');box.className="box";obj.innerHTML='<span>收起</span>';}else{R['boxLi'+idx].removeClass('current');R['boxPhoto'+idx].hide();R['boxLiBox'+idx].css('height','252px');box.className="box box_up";obj.innerHTML='查看全部户型('+len+')';}},toggleList:function(id,gid){var R=ADDetail.RUNTIME.LI,height=0,cls='';if(!R['boxLi'+id]){R['boxLi'+id]=$('#boxLi'+id);R['boxLiSlide'+id]=$('#boxLi'+id+' div.house_photo');}
if(!R['boxLiBox'+gid]){R['boxLiBox'+gid]=R['boxLi'+id].parent().parent();R['boxPhoto'+gid]=$('#box'+gid+' div.house_photo');R['boxLi'+gid]=$('#box'+gid+' li');}
cls=R['boxLiSlide'+id].css('display');height=parseInt(R['boxLiBox'+gid].css('height'));if(cls=='none'){R['boxLiSlide'+id].css('display','-webkit-box');R['boxLiBox'+gid].css('height',height+52+'px');R['boxLiSlide'+id].addClass('house_arrow');R['boxLi'+id].addClass('current');}else{R['boxLi'+id].removeClass('current');R['boxLiBox'+gid].css('height',height-52+'px');R['boxLiSlide'+id].css('display','none');R['boxLiSlide'+id].removeClass('house_arrow');}},resizeLayout:function(){if(!document.getElementById("#scroll_wrapper")){return;}
var R=ADDetail.RUNTIME;var scrollWidth=$("#scroll_wrapper")[0].offsetWidth;var imgWidth=$("#img_"+myScroll.currPageX)[0].offsetWidth;var scrollContainer=$("#scroller")[0];var indicator=$("#indicator")[0];scrollContainer.style.width=R.picCount*scrollContainer.parentNode.offsetWidth+"px";$('#thelist li').css({width:scrollWidth+'px'});if(myScroll){myScroll.refresh();myScroll.scrollToPage(myScroll.currPageX);}
indicator.style.bottom="auto";indicator.style.position="absolute";indicator.style.right="7px";indicator.style.top="142px";var more=$("a.btn_more"),boxContent=$("#summary")[0],oldHeight=boxContent.style.height;boxContent.style.height="auto";if(boxContent.offsetHeight>89){ADDetail.toogleMore((oldHeight=="auto"));more[0].parentNode.style.paddingBottom="0px";more.show();}else{ADDetail.toogleMore((oldHeight=="auto"));if(oldHeight!="auto")
more[0].parentNode.style.paddingBottom="10px";more.hide();}},switchIndex:function(obj){var box=obj.parentNode;if(box.className.indexOf("box_up")!=-1){box.className="box";obj.innerHTML='<span>收起</span>';}else{box.className="box box_up";obj.innerHTML='<span>更多</span>';}},toogleMore:function(boo){var more=$("a.btn_more")[0];var box=$("#summaryBox")[0];var boxContent=$("#summary")[0];if(boo){box.className="box box_hide";boxContent.style.height="auto";more.innerHTML='<span>收起</span>';}else{box.className="box box_up";boxContent.style.height="75px";more.innerHTML='<span>更多</span>';}},loadImg:function(idx){var pic=$("#img_"+idx)[0];var src=pic.getAttribute("src");var loading=pic.getAttribute("loading");if(!src||src.length==0||loading){return;}
img=new Image();img.idx=idx;img.addEventListener('load',function(){pic.style.background="none";pic.appendChild(this);this.style.width='auto';this.style.height='100%';this.style.marginLeft='auto';this.style.marginRight='auto';pic.removeAttribute("src");pic.removeAttribute("loading");this.onload=null;});img.src=src;pic.setAttribute("loading",true);},showHDImage:function(){var R=ADDetail.RUNTIME,images=[];for(var i=0,n=R.stData.images.length;i<n;i++){images[i]=R.stData.images[i].url;}
try{WeixinJSBridge.invoke('imagePreview',{'current':images[myScroll.currPageX],'urls':images});}catch(e){FCAPP.Common.msg(true,{noscroll:"true",msg:'请用微信进行调试'});}},goMap:function(id){id=id||'';FCAPP.Common.jumpTo('map.html',{id:id,rp:"ad-desc-1",'#wechat_webview_type':1},true);}};var ADDetail=FCAPP.ADDetail,myScroll;$(document).ready(ADDetail.init);